version: '2.1'
orbs:
  node: circleci/node@5.1.0

defaults: &defaults
  docker:
    - image: cimg/python:3.13
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

jobs:
  # === API ===
  deploy_app_to_railway:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project/
      - node/install:
          node-version: '20.9'
      - run: node --version
      - run: npm i -g @railway/cli
      - run:
          name: Deploy to Railway App
          command: |
            railway up --service=acceptable-amazement --detach || true
            echo "Deploy API completo"
  # === DASHBOARD ===
  deploy_dashboard_to_railway:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project/
      - node/install:
          node-version: '20.9'
      - run: node --version
      - run: npm i -g @railway/cli
      - run:
          name: Deploy Dashboard to Railway
          command: |
            # IMPORTANTE: en Railway (servicio dashboard) deja configurado:
            # Build type = Dockerfile, Dockerfile path = app/Dockerfile
            railway up --humble-freedom --detach || true
            echo "Deploy Dashboard completo"

tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/

workflows:
  version: 1
  deploy_pipeline:
    jobs:
      - deploy_app_to_railway:
          filters:
            branches:
              only:
                - main
      - deploy_dashboard_to_railway:
          requires:
            - deploy_app_to_railway      # dependencia
          filters:
            branches:
              only:
                - main