data_file: Calidad_del_Aire_enriquecido.csv

# --- Variables ---
target: 'Medicion'
model_name: "SVR"
features:
  - 'Municipio'
  - 'Estacion'
  - 'Año'
  - 'Mes'
  - 'Dia'
  - 'DiaSemana'
  - 'dia_del_anio'
  - 'semana_del_anio'
  - 'es_fin_de_semana'
  - 'mes_sin'
  - 'mes_cos'
  - 'dia_sin'
  - 'dia_cos'

categorical_features:
  - 'Municipio'
  - 'Estacion'
  - 'DiaSemana'

# --- Parámetros de división de datos ---
test_size: 0.2
random_state: 42

# --- Parámetros del modelo RandomForest ---
n_estimators: 300
max_depth: 15

# Parámetros específicos para ElasticNet
alpha: 0.01
l1_ratio: 1.0 

# Parámetros específicos para SVR
C: 15
gamma: 'auto'

# --- Parámetros de MLflow ---
mlflow_experiment_name: "Proyeccion_Calidad_Aire_Risaralda"
mlflow_tracking_uri: "http://52.23.182.67:5000"